#ifndef _REGISTEREXPORT_H_
#define _REGISTEREXPORT_H_
#include <afxwin.h>
#include <Windows.h>

class CRegisterExport
{
private:
	//Enumerate through all the sub key of a given key
	void EnumerateKey(HKEY hKey,CString strKey, FILE *fp, CString cstrFullPath);

	//Enumerate through all the values of a given key
	void EnumerateValues(HKEY hKey, CString cstrKey, FILE *fp, CString cstrFullPath);

	//To format the data with datatype as in .EXP file generated by REGEDIT....
	void FormatDataWithDataType(DWORD dwKeyType, LPBYTE pbbinKeyData, DWORD dwKeyDataLength, CString &cstrOutput);
	
	BOOL IsSubKey(HKEY hKey,LPCTSTR lpSubKey);
	BOOL IsExist(HKEY hKey,LPCTSTR lpSubKey);
public:
	//// Call this function with Rootkey name and filename. This enumerates through the keys 
	//// and subkeys and stores all its values.
	void ExportRegistry(CString cstrKeyRootName, CString cstrKeyName, CString cstrFileName);

	//使用ShellExecute方式导入导出注册表项
	void ShellExportRegister(LPCTSTR lpExportStr,LPCTSTR lpExportFile);
	void ShellImportRegister(LPCTSTR lpImportFile);
};

#endif